swagger: '2.0'
info:
  description: Una aplicacion web que busca información de un videojuego a partir de su título usando Wikipedia para obtener un resumen del juego, Spotify para encontrar su banda sonora, Twitch para encontrar streamings de jugadores en el momento, y Youtube para ver videos relacionados.
  version: "2.0"
  title: Info-Game
  contact:
    email: infogame@games.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
- name: games
  description: JSON de videojuegos con información 
  
paths:
  /games/:
    get:
      tags:
      - games
      summary: Get all games of the repository
      operationId: getAll
      produces:
      - application/json
      responses:
        200:
          description: Muestra todos los juegos
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
        400:
          description: bad input parameter
    post:
      tags:
      - games
      summary: Add a game
      produces:
      - application/json
      responses:
        200:
          description: Añade un videojuego
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
        400:
          description: bad input parameter
    put:
      tags:
      - games
      summary: Update a game
      produces:
      - application/json
      responses:
        200:
          description: Actualiza un videojuego
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
        400:
          description: bad input parameter

  /games/{title}:
    get:
      tags:
      - games
      summary: Get a game by title
      operationId: getGame
      produces:
      - application/json
      parameters:
      - name: title
        in: path
        description: Titulo del juego que buscas
        required: true
        type: string
      responses:
        200:
          description: Juego econtrado
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
        400:
          description: bad input parameter
    delete:
      tags:
      - games
      summary: Delete a game from repository by title
      operationId: deleteGame
      produces:
      - application/json
      parameters:
      - name: title
        in: path
        description: Titulo del juego deseas eliminar
        required: true
        type: string
      responses:
        200:
          description: Juego eleminado
          schema:
            type: array
            items:
              $ref: '#/definitions/Game'
        400:
          description: bad input parameter
    
definitions:
  Game:
    type: object
    required:
    - playlist
    - directo
    - video
    - descripcion
    properties:
      title:
        type: string
        example: "Dark Souls"
      playlist:
        type: string
        example: "Dark Souls Official Soundtrack"
      directo:
        type: string
        example: "http://www.twitch.tv/powerBazinga"
      video:
        type: string
        example: "Why is Dark Souls a Masterpiece?"
      descripcion:
        type: string
        example: "Es un videojuego de rol de acción, desarrollado por la empresa From Software para las plataformas PlayStation 3..."
      # Added by API Auto Mocking Plugin
basePath: /Info-Game/Info-Game/1.0.0
schemes:
 - https
# Added by API Auto Mocking Plugin
host: info-game-mashup.appspot.com